version: '3'

services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - data-platform

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # Internal + External listeners
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    networks:
      - data-platform

  spark:
    image: apache/spark:3.5.0
    container_name: spark
    command: >
      bash -c "/opt/spark/bin/spark-submit --master local[*]
      --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0
      --conf spark.jars.ivy=/tmp/.ivy2
      /app/services/spark/streaming_job.py"
    depends_on:
      - kafka
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ../:/app
      - ../data:/data
    networks:
      - data-platform
  
  simulator:
    build: ../services/simulator
    container_name: simulator
    depends_on:
      - kafka
    networks:
      - data-platform

  api:
    build: ../services/api
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - ../:/app
    working_dir: /app/services/api
    depends_on:
      - spark

  ui:
    build: ../services/ui
    container_name: ui
    ports:
      - "8501:8501"
    volumes:
      - ../:/app
    working_dir: /app/services/ui
    depends_on:
      - api

networks:
  data-platform:
    driver: bridge


  
